import React from 'react';
import { Link } from 'react-router-dom';
import InteractiveLogo from '../components/InteractiveLogo';
import '../styles/pages.css';

const LAST_UPDATED = 'August 5, 2026';

const TermsOfService = () => (
  <div className="legal-page">
    <header className="legal-header">
      <Link to="/" className="legal-brand">
        <InteractiveLogo width={28} height={28} />
        <span>tom.ai</span>
      </Link>
      <nav className="legal-nav">
        <Link to="/privacy">Privacy Policy</Link>
        <Link to="/login">Sign In</Link>
      </nav>
    </header>

    <article className="legal-card">
      <p className="legal-eyebrow">Legal</p>
      <h1>Terms of Service</h1>
      <p className="legal-updated">Last updated: {LAST_UPDATED}</p>

      <p className="legal-lead">
        Welcome to tom.ai. These Terms of Service (“Terms”) govern your access to and use of
        the tom.ai website, applications, and related services (collectively, the “Service”).
        By creating an account, signing in, or using the Service — including as a guest — you
        agree to these Terms.
      </p>

      <section>
        <h2>1. Who we are</h2>
        <p>
          tom.ai is a personal AI assistant that helps you chat, manage tasks, generate images,
          and optionally connect Google services such as Gmail, Calendar, and Tasks. The Service
          is provided “as is” for personal productivity use.
        </p>
      </section>

      <section>
        <h2>2. Eligibility &amp; accounts</h2>
        <p>
          You must be at least 13 years old (or the minimum age required in your country) to use
          the Service. You are responsible for keeping your login credentials secure and for all
          activity under your account. If you sign in with Google, you must also comply with
          Google’s applicable terms for that account.
        </p>
      </section>

      <section>
        <h2>3. Acceptable use</h2>
        <p>You agree not to misuse the Service. Without limitation, you will not:</p>
        <ul>
          <li>Violate any law or third-party rights</li>
          <li>Attempt to reverse engineer, disrupt, or overload the Service</li>
          <li>Upload malware, scrape the Service abusively, or probe for vulnerabilities</li>
          <li>Use the Service to generate or distribute harmful, deceptive, or illegal content</li>
          <li>Share another person’s private information without permission</li>
          <li>Resell or provide the Service as a hosted product without our written consent</li>
        </ul>
        <p>
          We may suspend or terminate access if we reasonably believe you have violated these Terms.
        </p>
      </section>

      <section>
        <h2>4. AI-generated content</h2>
        <p>
          Responses from tom.ai are generated by AI models and may be inaccurate, incomplete, or
          outdated. Do not rely on the Service as a substitute for professional advice (legal,
          medical, financial, or otherwise). You are responsible for how you use and share any
          output you receive.
        </p>
      </section>

      <section>
        <h2>5. Your content</h2>
        <p>
          You retain ownership of content you submit — including messages, tasks, uploaded
          documents, and prompts. By submitting content, you grant us a limited license to process
          it solely to operate, improve, and secure the Service (for example, retrieval for chat
          answers or task reminders). You represent that you have the rights needed to submit that
          content.
        </p>
      </section>

      <section>
        <h2>6. Third-party services</h2>
        <p>
          Features that connect to Google or other providers are optional. When you connect an
          integration, you authorize tom.ai to access only the scopes you approve, and you remain
          subject to that provider’s terms and privacy practices. We are not responsible for
          third-party outages or changes to their APIs.
        </p>
      </section>

      <section>
        <h2>7. Availability &amp; changes</h2>
        <p>
          We may update, suspend, or discontinue parts of the Service at any time. We may also
          revise these Terms. When we make material changes, we will update the “Last updated”
          date on this page. Continued use after changes means you accept the revised Terms.
        </p>
      </section>

      <section>
        <h2>8. Disclaimers</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF
          ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY — INCLUDING MERCHANTABILITY, FITNESS
          FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not guarantee uninterrupted or
          error-free operation.
        </p>
      </section>

      <section>
        <h2>9. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, tom.ai and its operators will not be liable for
          any indirect, incidental, special, consequential, or punitive damages, or for any loss of
          profits, data, or goodwill arising from your use of the Service. Our total liability for
          any claim relating to the Service will not exceed the greater of (a) the amount you paid
          us in the 12 months before the claim, or (b) USD $50.
        </p>
      </section>

      <section>
        <h2>10. Termination</h2>
        <p>
          You may stop using the Service at any time. We may terminate or restrict access if you
          breach these Terms or if we need to do so for security, legal, or operational reasons.
          Provisions that by nature should survive (including ownership, disclaimers, and
          limitation of liability) will survive termination.
        </p>
      </section>

      <section>
        <h2>11. Contact</h2>
        <p>
          Questions about these Terms? Reach us through the in-app support options or the contact
          channels listed on our website. For how we handle personal data, see our{' '}
          <Link to="/privacy">Privacy Policy</Link>.
        </p>
      </section>
    </article>

    <footer className="legal-footer">
      <Link to="/">← Back to tom.ai</Link>
    </footer>
  </div>
);

export default TermsOfService;
